trigger:
    - master

pr:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Test'

    - script: |
          npm ci

    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Test'

    - script: |
          npm test
      displayName: 'Run tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
          testRunner: JUnit
          testResultsFiles: 'reports/tests/**.xml'

    - task: PublishCodeCoverageResults@1
      inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: 'reports/coverage/cobertura-coverage.xml'
          reportDirectory: 'reports'
          failIfCoverageEmpty: true
